backend:
  name: git-gateway
  branch: main
media_folder: "src/img/recipes"
public_folder: "/img/recipes"

collections:
  - name: "recipes"
    label: "Recipes"
    folder: "src/recipes"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        summary: "{{fields.tag}}"
        field: { label: "Tag", name: "tag", widget: "string" }
      - {
          label: "Preparation time",
          name: "time",
          widget: "string",
          required: false,
        }
      - {
          label: "Number of servings",
          name: "servings",
          widget: "number",
          required: false,
        }
      - {
          label: "Servings unit",
          name: "servingsUnit",
          widget: "number",
          required: false,
        }
      - {
          label: "Source of the recipe",
          name: "sourceLabel",
          widget: "string",
          required: false,
        }
      - {
          label: "URL of the source of the recipe",
          name: "sourceURL",
          widget: "string",
          required: false,
        }
      - label: "Ingredients"
        name: "ingredients"
        widget: "list"
        summary: "{{fields.ingredient}}"
        field: { label: "Ingredient", name: "ingredient", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "settings"
    label: "Settings"
    files:
      - name: "site"
        label: "Site settings"
        delete: false
        file: "src/_data/site.json"
        fields:
          - {
              label: "Site name",
              name: "name",
              widget: "string",
              hint: "used for SEO",
            }
          - {
              label: "Site meta description",
              name: "metaDescription",
              widget: "string",
              hint: "used for SEO",
            }
